# Generated by Django 3.1.6 on 2022-09-09 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Название банка', max_length=255)),
                ('term_min', models.PositiveSmallIntegerField(default=10, help_text='Срок ипотеки, от', validators=[django.core.validators.MinValueValidator(10)])),
                ('term_max', models.PositiveSmallIntegerField(default=30, help_text='Срок ипотки, до', validators=[django.core.validators.MaxValueValidator(30)])),
                ('rate_min', models.FloatField(default=1.8, help_text='Ставка, от', validators=[django.core.validators.MinValueValidator(1.8)])),
                ('rate_max', models.FloatField(default=9.8, help_text='Cтавка, до', validators=[django.core.validators.MaxValueValidator(9.8)])),
                ('payment_min', models.PositiveIntegerField(default=1000000, help_text='Сумма кредита, от', validators=[django.core.validators.MinValueValidator(1000000)])),
                ('payment_max', models.PositiveIntegerField(default=10000000, help_text='Сумма кредите, до', validators=[django.core.validators.MaxValueValidator(10000000)])),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(term_min__lt=django.db.models.expressions.F('term_max')), name='mortgage_offer_terms_min_lt_terms_max'),
        ),
    ]
