# Generated by Django 3.1.6 on 2022-09-09 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='term_max',
            field=models.PositiveSmallIntegerField(default=30, help_text='Срок ипотеки, до', validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
