# Generated by Django 3.1.6 on 2022-09-09 18:02

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0003_auto_20220909_2057'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(rate_min__lt=django.db.models.expressions.F('rate_max')), name='mortgage_offer_rate_min_lt_rate_max'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(payment_min__lt=django.db.models.expressions.F('payment_max')), name='mortgage_offer_payment_min_lt_payment_max'),
        ),
    ]
