# Generated by Django 3.1.6 on 2022-09-10 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0004_auto_20220909_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='payment_max',
            field=models.PositiveIntegerField(default=10000000, help_text='Сумма кредита, до', validators=[django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
